<?php
declare(strict_types=1);

/*
  index.php
  - Reads a JSON file generated by your yt-dlp script
  - Renders each playlist as a <section>
  - Renders each video as an <article> with thumbnail + title (clickable)
  - Keeps your hamburger menu + left/right scrollers
*/

header('Content-Type: text/html; charset=utf-8');

$jsonFile = __DIR__ . '/channel_playlists_with_videos.json';

function h(string $s): string {
  return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function safe_rel_path(string $path): string {
  // Prevent directory traversal; only allow local relative paths like "thumbnails/abc.webp"
  $path = str_replace('\\', '/', $path);
  $path = ltrim($path, '/');
  if (str_contains($path, '..')) return '';
  return $path;
}

$data = null;
if (is_file($jsonFile)) {
  $raw = file_get_contents($jsonFile);
  if ($raw !== false) {
    $tmp = json_decode($raw, true);
    if (is_array($tmp)) $data = $tmp;
  }
}
$playlists = is_array($data['playlists'] ?? null) ? $data['playlists'] : [];

?>
<!doctype html>
<html lang="es">
  <head>
    <title>Plataforma de videos</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <style>
      *{margin:0px;padding:0px;}
      html,body{
        padding:0px;
        margin:0px;
        width:100%;
        height:100%;
        background:black;
        color:white;
        font-family:ubuntu,sans-serif;
        overflow-x:hidden;
      }
      nav{
        width:300px;
        background:midnightblue;
        position:fixed;
        height:100%;
        padding:20px;
        color:white;
        box-sizing:border-box;
        left:-300px;
        transition:all 1s;
        z-index:1000;
      }
      .sacado{ left:0px; }
      header,main,footer{padding:20px;}
      header{display:flex;align-items:center;justify-content: space-between;}
      header{position:fixed;top:0px;width:100%;background:black;box-sizing:border-box;z-index:900;}
      main{padding-top:100px;}

      section{width:100%;position:relative;margin-bottom:22px;}
      section h3{margin:0 0 10px 0;font-weight:700;}
      section .contenedor{
        display:flex;
        gap:20px;
        width:10000px;
        position:relative;
        transition:all 1s;
        left:10px;
      }

      section article{
        width:300px;
        height:170px;
        background:#1a1a1a;
        padding:10px;
        box-sizing:border-box;
        border-radius:5px;
        display:flex;
        gap:10px;
        align-items: flex-end;
        cursor:pointer;
        border:1px solid rgba(255,255,255,0.08);
      }
      section article:hover{
        border-color: rgba(255,255,255,0.20);
      }

      .thumb{
        width:120px;
        height:68px;
        object-fit:cover;
        border-radius:4px;
        background:#333;
        flex:0 0 auto;
      }
      .meta{
        display:flex;
        flex-direction:column;
        gap:6px;
        min-width:0;
        text-shadow:
            0 0 2px black,
            0 0 3px black,
            0 0 4px black;
      }
      .vtitle{
        font-size:14px;
        line-height:1.2;
        font-weight:700;
        white-space:nowrap;
        overflow:hidden;
        text-overflow:ellipsis;
        max-width:150px;
      }
      .vlink{
        font-size:12px;
        opacity:.75;
        white-space:nowrap;
        overflow:hidden;
        text-overflow:ellipsis;
        max-width:150px;
      }

      .izquierda,.derecha{
        position:absolute;
        top:50%;
        transform:translateY(-50%);
        background:black;
        color:white;
        width:40px;
        height:40px;
        font-size:20px;
        line-height:40px;
        text-align:center;
        border-radius:40px;
        transition:all 1s;
        opacity:0.1;
        font-weight:bold;
        user-select:none;
        cursor:pointer;
      }
      .izquierda{left:0px;}
      .derecha{right:0px;}
      .izquierda:hover,.derecha:hover{opacity:0.9;}

      .empty{
        padding:10px;
        opacity:.75;
      }
    </style>
  </head>
  <body>
    <nav>
      <div style="font-weight:700;margin-bottom:10px;">Menú</div>
      <div style="opacity:.85;">
        Playlists detectadas: <?= (int)count($playlists) ?>
      </div>
    </nav>

    <header>
      <h1 style="font-size:20px;">Logo</h1>
      <div id="hamburguesa" style="font-size:22px;cursor:pointer;">☰</div>
    </header>

    <main>
      <?php if (!$playlists): ?>
        <div class="empty">
          No se pudo leer <b><?= h(basename($jsonFile)) ?></b> o no contiene playlists.<br>
          Asegúrate de que el JSON esté en: <code><?= h($jsonFile) ?></code>
        </div>
      <?php endif; ?>

      <?php foreach ($playlists as $pl): ?>
        <?php
          $plTitle = (string)($pl['title'] ?? 'Sin título');
          $videos  = is_array($pl['videos'] ?? null) ? $pl['videos'] : [];
        ?>
        <section>
          <h3><?= h($plTitle) ?></h3>

          <div class="contenedor" style="left:0px;">
            <?php if (!$videos): ?>
              <article style="width:300px;height:120px;align-items:center;">
                <div class="meta">
                  <div class="vtitle">Sin vídeos</div>
                  <div class="vlink">—</div>
                </div>
              </article>
            <?php endif; ?>

            <?php foreach ($videos as $v): ?>
              <?php
                $vid   = (string)($v['id'] ?? '');
                $vttl  = (string)($v['title'] ?? 'Sin título');
                $vurl  = (string)($v['url'] ?? '#');
                $thumb = (string)($v['thumbnail_file'] ?? '');

                $thumb = safe_rel_path($thumb);
                $thumbExists = $thumb && is_file(__DIR__ . '/' . $thumb);
                $thumbSrc = $thumbExists ? $thumb : '';
              ?>
              <article data-url="<?= h($vurl) ?>" style="background:url(<?= h($thumbSrc) ?>);background-size:cover;">
               
                <div class="meta">
                  <div class="vtitle" title="<?= h($vttl) ?>"><?= h($vttl) ?></div>
                  <div class="vlink" title="<?= h($vurl) ?>"><?= h($vurl) ?></div>
                </div>
              </article>
            <?php endforeach; ?>
          </div>

          <div class="izquierda">🡠</div>
          <div class="derecha">🡢</div>
        </section>
      <?php endforeach; ?>
    </main>

    <footer></footer>

    <script>
      // BOTON HAMBURGUESA //////////////////////////////////////////////////////////////////////
      var abierto = false;
      let hamburguesa = document.querySelector("#hamburguesa")
      let navegacion = document.querySelector("nav");
      hamburguesa.onclick = function(){
        if(abierto){
           hamburguesa.textContent = "☰"
           navegacion.classList.remove("sacado");
           abierto = false;
        }else{
          hamburguesa.textContent = "🗙"
          navegacion.classList.add("sacado");
          abierto = true;
        }
      }

      // CLICK EN TARJETA: abrir video /////////////////////////////////////////////////////////
      document.querySelectorAll("section article[data-url]").forEach(function(card){
        card.addEventListener("click", function(){
          const url = this.getAttribute("data-url");
          if(url && url !== "#") window.open(url, "_blank", "noopener");
        });
      });

      // BOTONES IZQUIERDA Y DERECHA ///////////////////////////////////////////////////////////
      let izquierdas = document.querySelectorAll(".izquierda")
      izquierdas.forEach(function(izquierda){
        izquierda.onclick = function(){
          let tira = this.parentElement.querySelector(':scope > .contenedor');
          let actual = parseFloat(tira.style.left || "0")
          tira.style.left = (actual+320)+"px"
        }
      })
      let derechas = document.querySelectorAll(".derecha")
      derechas.forEach(function(derecha){
        derecha.onclick = function(){
          let tira = this.parentElement.querySelector(':scope > .contenedor');
          let actual = parseFloat(tira.style.left || "0")
          tira.style.left = (actual-320)+"px"
        }
      })
    </script>
  </body>
</html>

