<?php
declare(strict_types=1);

/*
  index.php
  - Reads a JSON file generated by your yt-dlp script
  - Renders each playlist as a <section>
  - Renders each video as an <article> with thumbnail + title (clickable)
  - On click: opens a floating modal card (thumbnail + title + description + button to YouTube)
  - Keeps your hamburger menu + left/right scrollers
*/

header('Content-Type: text/html; charset=utf-8');

$jsonFile = __DIR__ . '/channel_playlists_with_videos.json';

function h(string $s): string {
  return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function safe_rel_path(string $path): string {
  // Prevent directory traversal; only allow local relative paths like "thumbnails/abc.webp"
  $path = str_replace('\\', '/', $path);
  $path = ltrim($path, '/');
  if (str_contains($path, '..')) return '';
  return $path;
}

$data = null;
if (is_file($jsonFile)) {
  $raw = file_get_contents($jsonFile);
  if ($raw !== false) {
    $tmp = json_decode($raw, true);
    if (is_array($tmp)) $data = $tmp;
  }
}
$playlists = is_array($data['playlists'] ?? null) ? $data['playlists'] : [];

?>
<!doctype html>
<html lang="es">
  <head>
    <title>Plataforma de videos</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <style>
      *{margin:0px;padding:0px;}
      html,body{
        padding:0px;
        margin:0px;
        width:100%;
        height:100%;
        background:black;
        color:white;
        font-family:ubuntu,sans-serif;
        overflow-x:hidden;
      }
      nav{
        width:300px;
        background:midnightblue;
        position:fixed;
        height:100%;
        padding:20px;
        color:white;
        box-sizing:border-box;
        left:-300px;
        transition:all 1s;
        z-index:1000;
      }
      .sacado{ left:0px; }
      header,main,footer{padding:20px;}
      header{display:flex;align-items:center;justify-content: space-between;}
      header{position:fixed;top:0px;width:100%;background:black;box-sizing:border-box;z-index:900;}
      main{padding-top:100px;}

      section{width:100%;position:relative;margin-bottom:22px;}
      section h3{margin:0 0 10px 0;font-weight:700;}
      section .contenedor{
        display:flex;
        gap:20px;
        width:10000px;
        position:relative;
        transition:all 1s;
        left:10px;
      }

      section article{
        width:300px;
        height:170px;
        background:#1a1a1a;
        padding:10px;
        box-sizing:border-box;
        border-radius:5px;
        display:flex;
        gap:10px;
        align-items: flex-end;
        cursor:pointer;
        border:1px solid rgba(255,255,255,0.08);
        position:relative;
        overflow:hidden;
      }
      section article:hover{
        border-color: rgba(255,255,255,0.20);
      }

      .thumb{
        width:120px;
        height:68px;
        object-fit:cover;
        border-radius:4px;
        background:#333;
        flex:0 0 auto;
      }
      .meta{
        display:flex;
        flex-direction:column;
        gap:6px;
        min-width:0;
        text-shadow:
            0 0 2px black,
            0 0 3px black,
            0 0 4px black;
      }
      .vtitle{
        font-size:14px;
        line-height:1.2;
        font-weight:700;
        white-space:nowrap;
        overflow:hidden;
        text-overflow:ellipsis;
        max-width:240px;
      }
      .vlink{
        font-size:12px;
        opacity:.75;
        white-space:nowrap;
        overflow:hidden;
        text-overflow:ellipsis;
        max-width:240px;
      }

      .izquierda,.derecha{
        position:absolute;
        top:50%;
        transform:translateY(-50%);
        background:black;
        color:white;
        width:40px;
        height:40px;
        font-size:20px;
        line-height:40px;
        text-align:center;
        border-radius:40px;
        transition:all 1s;
        opacity:0.1;
        font-weight:bold;
        user-select:none;
        cursor:pointer;
      }
      .izquierda{left:0px;}
      .derecha{right:0px;}
      .izquierda:hover,.derecha:hover{opacity:0.9;}

      .empty{
        padding:10px;
        opacity:.75;
      }

      /* =========================
         MODAL
      ========================= */
      .modalOverlay{
        position:fixed;
        inset:0;
        background:rgba(0,0,0,.72);
        display:none;
        align-items:center;
        justify-content:center;
        z-index:2000;
        padding:20px;
        box-sizing:border-box;
      }
      .modalOverlay.abierto{ display:flex; }

      .modalCard{
        width:min(920px, 96vw);
        background:#0f0f0f;
        border:1px solid rgba(255,255,255,.12);
        border-radius:10px;
        overflow:hidden;
        box-shadow:0 20px 60px rgba(0,0,0,.6);
        display:flex;
        gap:0;
      }

      .modalMedia{
        width:min(520px, 55vw);
        background:#111;
        position:relative;
        flex:0 0 auto;
      }
      .modalMedia img{
        width:100%;
        height:100%;
        max-height:420px;
        object-fit:cover;
        display:block;
        background:#222;
      }

      .modalBody{
        padding:16px 16px 14px 16px;
        box-sizing:border-box;
        display:flex;
        flex-direction:column;
        gap:10px;
        flex:1 1 auto;
        min-width:0;
      }
      .modalTop{
        display:flex;
        align-items:flex-start;
        justify-content:space-between;
        gap:12px;
      }
      .modalTitle{
        font-size:18px;
        font-weight:800;
        line-height:1.2;
        max-width:100%;
        overflow:hidden;
        text-overflow:ellipsis;
      }
      .modalClose{
        flex:0 0 auto;
        width:34px;
        height:34px;
        border-radius:999px;
        border:1px solid rgba(255,255,255,.16);
        background:rgba(255,255,255,.06);
        color:white;
        cursor:pointer;
        font-size:18px;
        line-height:32px;
        text-align:center;
        user-select:none;
      }
      .modalClose:hover{ background:rgba(255,255,255,.12); }

      .modalMetaLine{
        font-size:12px;
        opacity:.75;
        overflow:hidden;
        text-overflow:ellipsis;
        white-space:nowrap;
      }

      .modalDesc{
        font-size:13px;
        line-height:1.45;
        opacity:.90;
        max-height:180px;
        overflow:auto;
        padding-right:6px;
      }
      .modalDesc::-webkit-scrollbar{ width:8px; }
      .modalDesc::-webkit-scrollbar-thumb{ background:rgba(255,255,255,.12); border-radius:8px; }

      .modalActions{
        display:flex;
        gap:10px;
        margin-top:auto;
        padding-top:6px;
      }
      .btn{
        display:inline-flex;
        align-items:center;
        justify-content:center;
        padding:10px 12px;
        border-radius:8px;
        border:1px solid rgba(255,255,255,.16);
        background:rgba(255,255,255,.06);
        color:white;
        text-decoration:none;
        cursor:pointer;
        font-weight:700;
        font-size:13px;
        user-select:none;
      }
      .btn:hover{ background:rgba(255,255,255,.12); }
      .btnPrimary{
        border-color: rgba(120,160,255,.40);
        background: rgba(120,160,255,.16);
      }
      .btnPrimary:hover{ background: rgba(120,160,255,.24); }

      @media (max-width: 780px){
        .modalCard{ flex-direction:column; }
        .modalMedia{ width:100%; }
        .modalMedia img{ max-height:260px; }
      }
    </style>
  </head>
  <body>
    <nav>
      <div style="font-weight:700;margin-bottom:10px;">Menú</div>
      <div style="opacity:.85;">
        Playlists detectadas: <?= (int)count($playlists) ?>
      </div>
    </nav>

    <header>
      <h1 style="font-size:20px;">Logo</h1>
      <div id="hamburguesa" style="font-size:22px;cursor:pointer;">☰</div>
    </header>

    <main>
      <?php if (!$playlists): ?>
        <div class="empty">
          No se pudo leer <b><?= h(basename($jsonFile)) ?></b> o no contiene playlists.<br>
          Asegúrate de que el JSON esté en: <code><?= h($jsonFile) ?></code>
        </div>
      <?php endif; ?>

      <?php foreach ($playlists as $pl): ?>
        <?php
          $plTitle = (string)($pl['title'] ?? 'Sin título');
          $videos  = is_array($pl['videos'] ?? null) ? $pl['videos'] : [];
        ?>
        <section>
          <h3><?= h($plTitle) ?></h3>

          <div class="contenedor" style="left:0px;">
            <?php if (!$videos): ?>
              <article style="width:300px;height:120px;align-items:center;">
                <div class="meta">
                  <div class="vtitle">Sin vídeos</div>
                  <div class="vlink">—</div>
                </div>
              </article>
            <?php endif; ?>

            <?php foreach ($videos as $v): ?>
              <?php
                $vid   = (string)($v['id'] ?? '');
                $vttl  = (string)($v['title'] ?? 'Sin título');
                $vurl  = (string)($v['url'] ?? '#');
                $desc  = (string)($v['description'] ?? ($v['descripcion'] ?? ''));

                $thumb = (string)($v['thumbnail_file'] ?? '');
                $thumb = safe_rel_path($thumb);
                $thumbExists = $thumb && is_file(__DIR__ . '/' . $thumb);
                $thumbSrc = $thumbExists ? $thumb : '';
              ?>
              <article
                data-url="<?= h($vurl) ?>"
                data-title="<?= h($vttl) ?>"
                data-desc="<?= h($desc) ?>"
                data-thumb="<?= h($thumbSrc) ?>"
                style="background:url(<?= h($thumbSrc) ?>);background-size:cover;"
              >
                <div class="meta">
                  <div class="vtitle" title="<?= h($vttl) ?>"><?= h($vttl) ?></div>
                  <div class="vlink" title="<?= h($vurl) ?>"><?= h($vurl) ?></div>
                </div>
              </article>
            <?php endforeach; ?>
          </div>

          <div class="izquierda">🡠</div>
          <div class="derecha">🡢</div>
        </section>
      <?php endforeach; ?>
    </main>

    <footer></footer>

    <!-- MODAL -->
    <div class="modalOverlay" id="modalOverlay" aria-hidden="true">
      <div class="modalCard" role="dialog" aria-modal="true" aria-label="Detalles del vídeo" id="modalCard">
        <div class="modalMedia">
          <img id="modalThumb" alt="Miniatura del vídeo" src="">
        </div>
        <div class="modalBody">
          <div class="modalTop">
            <div style="min-width:0;">
              <div class="modalTitle" id="modalTitle"></div>
              <div class="modalMetaLine" id="modalUrl"></div>
            </div>
            <div class="modalClose" id="modalClose" title="Cerrar">✕</div>
          </div>

          <div class="modalDesc" id="modalDesc"></div>

          <div class="modalActions">
            <a class="btn btnPrimary" id="modalGo" href="#" target="_blank" rel="noopener">Ver en YouTube</a>
            <div class="btn" id="modalCancel">Cerrar</div>
          </div>
        </div>
      </div>
    </div>

    <script>
      // BOTON HAMBURGUESA //////////////////////////////////////////////////////////////////////
      var abierto = false;
      let hamburguesa = document.querySelector("#hamburguesa")
      let navegacion = document.querySelector("nav");
      hamburguesa.onclick = function(){
        if(abierto){
           hamburguesa.textContent = "☰"
           navegacion.classList.remove("sacado");
           abierto = false;
        }else{
          hamburguesa.textContent = "🗙"
          navegacion.classList.add("sacado");
          abierto = true;
        }
      }

      // BOTONES IZQUIERDA Y DERECHA ///////////////////////////////////////////////////////////
      let izquierdas = document.querySelectorAll(".izquierda")
      izquierdas.forEach(function(izquierda){
        izquierda.onclick = function(){
          let tira = this.parentElement.querySelector(':scope > .contenedor');
          let actual = parseFloat(tira.style.left || "0")
          tira.style.left = (actual+320)+"px"
        }
      })
      let derechas = document.querySelectorAll(".derecha")
      derechas.forEach(function(derecha){
        derecha.onclick = function(){
          let tira = this.parentElement.querySelector(':scope > .contenedor');
          let actual = parseFloat(tira.style.left || "0")
          tira.style.left = (actual-320)+"px"
        }
      })

      // MODAL LOGIC ///////////////////////////////////////////////////////////////////////////
      const overlay   = document.getElementById("modalOverlay");
      const card      = document.getElementById("modalCard");
      const mThumb    = document.getElementById("modalThumb");
      const mTitle    = document.getElementById("modalTitle");
      const mDesc     = document.getElementById("modalDesc");
      const mUrl      = document.getElementById("modalUrl");
      const mGo       = document.getElementById("modalGo");
      const mClose    = document.getElementById("modalClose");
      const mCancel   = document.getElementById("modalCancel");

      function openModal({title, desc, url, thumb}){
        mTitle.textContent = title || "Sin título";
        mUrl.textContent   = url || "";
        mGo.href           = url || "#";

        const d = (desc || "").trim();
        mDesc.textContent = d ? d : "Sin descripción.";

        if (thumb) {
          mThumb.src = thumb;
          mThumb.style.display = "block";
        } else {
          mThumb.removeAttribute("src");
          mThumb.style.display = "none";
        }

        overlay.classList.add("abierto");
        overlay.setAttribute("aria-hidden", "false");
        // focus close for accessibility
        mClose.focus?.();
      }

      function closeModal(){
        overlay.classList.remove("abierto");
        overlay.setAttribute("aria-hidden", "true");
        // clear
        mGo.href = "#";
      }

      // CLICK EN TARJETA: abrir modal (NO ir a youtube directo) ///////////////////////////////
      document.querySelectorAll("section article[data-url]").forEach(function(cardEl){
        cardEl.addEventListener("click", function(){
          const url   = this.getAttribute("data-url")   || "";
          const title = this.getAttribute("data-title") || "";
          const desc  = this.getAttribute("data-desc")  || "";
          const thumb = this.getAttribute("data-thumb") || "";

          if(!url || url === "#") return;

          openModal({title, desc, url, thumb});
        });
      });

      // cerrar con X y botón cerrar
      mClose.addEventListener("click", closeModal);
      mCancel.addEventListener("click", closeModal);

      // cerrar click fuera
      overlay.addEventListener("click", function(e){
        if (e.target === overlay) closeModal();
      });

      // evitar que click dentro cierre por burbujeo (por seguridad)
      card.addEventListener("click", function(e){ e.stopPropagation(); });

      // cerrar con ESC
      document.addEventListener("keydown", function(e){
        if(e.key === "Escape" && overlay.classList.contains("abierto")) closeModal();
      });
    </script>
  </body>
</html>

